// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYC0SABhr3fWI-yhGrHjgU1stKnxtWjPw',
    appId: '1:770365428478:web:2a95ea34876c1277778baf',
    messagingSenderId: '770365428478',
    projectId: 'topicdetection-93c2e',
    authDomain: 'topicdetection-93c2e.firebaseapp.com',
    storageBucket: 'topicdetection-93c2e.appspot.com',
    measurementId: 'G-NWZ7PDFMBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV-gPQcSE6_rAxYa4HdZP_Zn3bxQV-2f0',
    appId: '1:770365428478:android:57454e6bf7293bab778baf',
    messagingSenderId: '770365428478',
    projectId: 'topicdetection-93c2e',
    storageBucket: 'topicdetection-93c2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoVDXvf9j1pk2uI5Ot7hk9VdB8D357Cmg',
    appId: '1:770365428478:ios:4aefbc178da829ae778baf',
    messagingSenderId: '770365428478',
    projectId: 'topicdetection-93c2e',
    storageBucket: 'topicdetection-93c2e.appspot.com',
    iosBundleId: 'com.example.topicdetectionweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoVDXvf9j1pk2uI5Ot7hk9VdB8D357Cmg',
    appId: '1:770365428478:ios:af73d0d9a278600b778baf',
    messagingSenderId: '770365428478',
    projectId: 'topicdetection-93c2e',
    storageBucket: 'topicdetection-93c2e.appspot.com',
    iosBundleId: 'com.example.topicdetectionweb.RunnerTests',
  );
}
